site_name: 'cppproptest'
site_description: 'C++ Property Testing'
site_author: 'kindone'
site_url: 'https://github.com/pages/kindone/cppproptest'

repo_name: 'kindone/cppproptest'
repo_url: 'https://github.com/kindone/cppproptest'
edit_uri: 'edit/master/docs'

theme:
  name: material
  font:
    text: 'Inter'
    code: 'Spline Sans Mono' # 'Inconsolata'
  palette:
    primary: teal
    accent: light green
  favicon: assets/favicon.ico
  features:
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - toc.follow
    - navigation.top
    - search.highlight
    - search.suggest
    - navigation.expand

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - meta
  - footnotes
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized
  - kroki:
      http_method: POST

nav:
  - 'cppproptest':
    - README.md
    - 'Getting Started' : GettingStarted.md
    - 'Step-by-Step Walkthrough' : Walkthrough.md
    - PropertyAPI.md
    - 'Generating Inputs':
      - Generators.md
      - Combinators.md
      - 'Real World Examples' : GeneratorExamples.md
    - 'Shrinking - Simplifying Failed Inputs': Shrinking.md
    - 'Displaying Custom Types': Printing.md
    - 'Stateful & Concurrency Testing':
      - StatefulTesting.md
      - ConcurrencyTesting.md
      - 'Advanced Scenarios' : AdvancedStatefulTesting.md
    - 'Tips & Best Practices':
      - TestStrategies.md
